import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@fontsource/montserrat";
import Footer from "../components/FooterComponent";
import Header from "../components/Header";
import { ReactNode } from "react";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
